function finalDatasetWithRain = importRainData(filename, dataLines)
%IMPORTFILE6 Import data from a text file
%  FINALDATASETWITHRAIN = IMPORTFILE6(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  FINALDATASETWITHRAIN = IMPORTFILE6(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  finalDatasetWithRain = importfile6("C:\Users\MathWorks\MATLAB Drive\kaggledata\finalDatasetWithRain.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-May-2025 10:33:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["lat", "lon", "time", "omega_x", "omega_y", "omega", "pr_wtr", "rhum_x", "rhum_y", "rhum", "slp", "tmp_x", "tmp_y", "tmp", "uwnd_x", "uwnd_y", "uwnd", "vwnd_x", "vwnd_y", "vwnd", "rain"];
opts.VariableTypes = ["double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "time", "InputFormat", "yyyy-MM-dd", "DatetimeFormat", "preserveinput");

% Import the data
finalDatasetWithRain = readtable(filename, opts);

end